import os
import time
import sys
import traceback
from notebooklm_tools.core.auth import load_cached_tokens
from notebooklm_tools.core.client import NotebookLMClient

# --- Configuration ---
NOTEBOOK_ID = "d564fe9e-3a07-4c14-b73c-99361a716d24" # Existing notebook with 43 sources
OUTPUT_FILENAME = "BTS_Comeback_2026_blog.md"
LOG_FILENAME = "bts_comeback_resume_log.txt"

def log(message):
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    log_msg = f"[{timestamp}] {message}"
    print(log_msg)
    with open(LOG_FILENAME, "a", encoding="utf-8") as f:
        f.write(log_msg + "\n")

def main():
    log("======================================================================")
    log(f"RESUMING BTS Blog Generation")
    log(f"Notebook ID: {NOTEBOOK_ID}")
    log("======================================================================")

    try:
        # 1. Initialize Client
        tokens = load_cached_tokens()
        client = NotebookLMClient(cookies=tokens.cookies)
        log("[OK] Client initialized")
        log("")

        # 2. Generate Blog Post
        log("[1/2] Generating blog post (create_report)...")
        
        try:
            # Using create_report compatible with the client
            blog = client.create_report(
                notebook_id=NOTEBOOK_ID,
                report_format="Blog Post",
                language="ko"
            )
            
            # NotebookLMClient might return dict or object
            generation_id = blog.get('artifact_id') if isinstance(blog, dict) else getattr(blog, 'artifact_id', None)
            
            if not generation_id:
                # Try outputting what we got to debug
                log(f"Warning: Could not extract generation_id from: {blog}")
                # Some versions might return just the ID or different structure?
                # Assuming standard behavior for now.
            
            log(f"  Artifact ID: {generation_id}")
            log("  Waiting for generation (60s)...")
            time.sleep(60)

            # 3. Download Content
            log("[2/2] Downloading content...")
            report_content = None
            for i in range(15):
                try:
                    # Using download_report for consistency
                    client.download_report(NOTEBOOK_ID, OUTPUT_FILENAME, generation_id)
                    
                    if os.path.exists(OUTPUT_FILENAME):
                        with open(OUTPUT_FILENAME, 'r', encoding='utf-8') as f:
                            report_content = f.read()
                        if len(report_content) > 100:
                            break
                    else:
                         log(f"  Attempt {i+1}: file not created yet")
                    
                except Exception as e:
                    log(f"  Attempt {i+1}: report not ready {e}")
                    time.sleep(10)

            if report_content:
                # Append footer
                footer = f"\n\n---\n*Generated by NotebookLM with Deep Research sources.*"
                with open(OUTPUT_FILENAME, "a", encoding="utf-8") as f:
                    f.write(footer)
                
                print("")
                log("======================================================================")
                log("SUCCESS!")
                log("======================================================================")
                log(f"  File: {OUTPUT_FILENAME}")
                log(f"  Size: {len(report_content)} characters")
            else:
                 log("FAILED to download generated content.")
                 raise Exception("Content download failed")

        except Exception as e:
             log(f"Generation error: {e}")
             raise e

    except Exception as e:
        print("")
        log("======================================================================")
        log(f"ERROR: {str(e)}")
        log(traceback.format_exc())
        log("======================================================================")
        sys.exit(1)

if __name__ == "__main__":
    main()
